# Generated by Django 2.0.9 on 2018-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('mobile_number', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'studinfo',
            },
        ),
    ]
